# Independent settings for the local costmap
local_costmap:
  map_type: costmap

  global_frame    : odom
  robot_base_frame: base_footprint
  transform_tolerance: 0.3

  update_frequency : 10.0
  publish_frequency: 1.0

  rolling_window: true
  width         : 4.0
  height        : 4.0
  resolution    : 0.025

  robot_radius: 0.275

  #plugins are loaded in a separate yaml file


  obstacle_laser_layer:
    enabled: true
    observation_sources: base_scan
    combination_method: 0 # can erase static layer

    base_scan:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: scan
      expected_update_rate: 0.3
      observation_persistence: 1.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 6.0
      obstacle_range: 5.5

  obstacle_sonar_layer:
    enabled: false
    ns: ""
    topics: ["/sonar_base"]
    no_readings_timeout: 0.0
    clear_threshold: 0.20
    mark_threshold: 0.80
    clear_on_max_reading: true

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.55
    cost_scaling_factor: 25.0
